# Generated by Django 4.0.3 on 2022-03-29 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('summary', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('date', models.DateField()),
                ('account_credit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit', to='accounts.account', verbose_name='credit')),
                ('account_debit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debit', to='accounts.account', verbose_name='debit')),
            ],
        ),
    ]
